[2013-09-02 16:25:44] log.ERROR: exception 'RuntimeException' with message 'Not enough arguments.' in D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Input\Input.php:76
Stack trace:
#0 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(239): Symfony\Component\Console\Input\Input->validate()
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Console\Command.php(96): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Application.php(897): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Application.php(191): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MakeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 D:\vhosts\laraveil\artisan(59): Symfony\Component\Console\Application->run()
#6 {main} [] []
[2013-09-02 16:29:41] log.ERROR: exception 'RuntimeException' with message 'Not enough arguments.' in D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Input\Input.php:76
Stack trace:
#0 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(239): Symfony\Component\Console\Input\Input->validate()
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Console\Command.php(96): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Application.php(897): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Application.php(191): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MakeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 D:\vhosts\laraveil\artisan(59): Symfony\Component\Console\Application->run()
#6 {main} [] []
[2013-09-02 16:31:45] log.ERROR: exception 'RuntimeException' with message 'Not enough arguments.' in D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Input\Input.php:76
Stack trace:
#0 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(239): Symfony\Component\Console\Input\Input->validate()
#1 D:\vhosts\laraveil\vendor\laravel\framework\src\Illuminate\Console\Command.php(96): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Application.php(897): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Application.php(191): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MakeCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 D:\vhosts\laraveil\vendor\symfony\console\Symfony\Component\Console\Application.php(121): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 D:\vhosts\laraveil\artisan(59): Symfony\Component\Console\Application->run()
#6 {main} [] []
[2013-09-02 16:46:23] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Models\Article' not found' in D:\vhosts\laraveil\app\database\seeds\ContentSeeder.php:13
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-02 16:48:16] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'app\models\article' not found' in D:\vhosts\laraveil\app\database\seeds\ContentSeeder.php:13
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-02 16:49:54] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Models\Article' not found' in D:\vhosts\laraveil\app\database\seeds\ContentSeeder.php:13
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-02 16:52:04] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Models\Article' not found' in D:\vhosts\laraveil\app\database\seeds\ContentSeeder.php:13
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-02 16:53:16] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Models\Article' not found' in D:\vhosts\laraveil\app\database\seeds\ContentSeeder.php:14
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-02 16:55:21] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Models\Article' not found' in D:\vhosts\laraveil\app\database\seeds\ContentSeeder.php:14
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-02 16:56:21] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Models\Article' not found' in D:\vhosts\laraveil\app\database\seeds\ContentSeeder.php:14
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-02 16:57:33] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Models\Article' not found' in D:\vhosts\laraveil\app\database\seeds\ContentSeeder.php:14
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-02 16:58:11] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Models\Article' not found' in D:\vhosts\laraveil\app\database\seeds\ContentSeeder.php:14
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-02 17:00:29] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Models\Article' not found' in D:\vhosts\laraveil\app\database\seeds\ContentSeeder.php:14
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-02 17:04:24] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Models\Article' not found' in D:\vhosts\laraveil\app\database\seeds\ContentSeeder.php:12
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-02 17:06:42] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Models\Article' not found' in D:\vhosts\laraveil\app\database\seeds\ContentSeeder.php:12
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2013-09-02 17:08:22] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'App\Models\Article' not found' in D:\vhosts\laraveil\app\database\seeds\ContentSeeder.php:12
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
